pozivni = {
    "01": {"mjesto_operater": "Grad Zagreb i Zagrebacka zupanija", "vrsta": "fiksna mreza"},
    "020": {"mjesto_operater": "Dubrovacko-neretvanska zupanija", "vrsta": "fiksna mreza"},
    "021": {"mjesto_operater": "Splitsko-dalmatinska zupanija", "vrsta": "fiksna mreza"},
    "022": {"mjesto_operater": "Sibensko-kninska zupanija", "vrsta": "fiksna mreza"},
    "023": {"mjesto_operater": "Zadarska zupanija", "vrsta": "fiksna mreza"},
    "031": {"mjesto_operater": "Osjecko-baranjska zupanija", "vrsta": "fiksna mreza"},
    "032": {"mjesto_operater": "Vukovarsko-srijemska zupanija", "vrsta": "fiksna mreza"},
    "033": {"mjesto_operater": "Viroviticko-podravska zupanija", "vrsta": "fiksna mreza"},
    "034": {"mjesto_operater": "Pozesko-slavonska zupanija", "vrsta": "fiksna mreza"},
    "035": {"mjesto_operater": "Brodsko-posavska zupanija", "vrsta": "fiksna mreza"},
    "040": {"mjesto_operater": "Medimurska zupanija", "vrsta": "fiksna mreza"},
    "042": {"mjesto_operater": "Varazdinska zupanija", "vrsta": "fiksna mreza"},
    "043": {"mjesto_operater": "Bjelovarsko-bilogorska zupanija", "vrsta": "fiksna mreza"},
    "044": {"mjesto_operater": "Sisacko-moslavacka zupanija", "vrsta": "fiksna mreza"},
    "047": {"mjesto_operater": "Karlovacka zupanija", "vrsta": "fiksna mreza"},
    "048": {"mjesto_operater": "Koprivnicko-krizevacka zupanija", "vrsta": "fiksna mreza"},
    "049": {"mjesto_operater": "Krapinsko-zagorska zupanija", "vrsta": "fiksna mreza"},
    "051": {"mjesto_operater": "Primorsko-goranska zupanija", "vrsta": "fiksna mreza"},
    "052": {"mjesto_operater": "Istarska zupanija", "vrsta": "fiksna mreza"},
    "053": {"mjesto_operater": "Licko-senjska zupanija", "vrsta": "fiksna mreza"},
    "091": {"mjesto_operater": "A1 Hrvatska", "vrsta": "mobilna mreza"},
    "092": {"mjesto_operater": "Tomato", "vrsta": "mobilna mreza"},
    "095": {"mjesto_operater": "Telemach", "vrsta": "mobilna mreza"},
    "097": {"mjesto_operater": "bonbon", "vrsta": "mobilna mreza"},
    "098": {"mjesto_operater": "Hrvatski Telekom", "vrsta": "mobilna mreza"},
    "099": {"mjesto_operater": "Hrvatski Telekom", "vrsta": "mobilna mreza"},
    "0800": {"mjesto_operater": "Besplatni pozivi", "vrsta": "Posebne usluge"},
    "060": {"mjesto_operater": "Komercijalni pozivi", "vrsta": "Posebne usluge"},
    "061": {"mjesto_operater": "Glasovanje telefonom", "vrsta": "Posebne usluge"},
    "064": {"mjesto_operater": "Usluge s neprimjerenim sadrzajem", "vrsta": "Posebne usluge"},
    "065": {"mjesto_operater": "Nagradne igre", "vrsta": "Posebne usluge"},
    "069": {"mjesto_operater": "Usluge namijenjene djeci", "vrsta": "Posebne usluge"},
    "072": {"mjesto_operater": "jedinstveni pristupni broj za cijelu drzavu za posebne usluge", "vrsta": "Posebne usluge"},

}